### ISSUE TITLE
Can't find praat folder on MacOS

### ISSUE THREAD

**Issue by Karlemami** [orhunulusahin/praatvscode#1]
Hello,

I'm on a M1 Macbook air.
I first defined path as "/Applications/Praat.app", but I got the error message "ApplicationsPraat.appContentsMacOSPraat.appContentsMacOSPraat: No such file or directory" when i tried to run a praat script.
I changed the path to "/Applications/Praat.app/Contents/MacOS/", but got the same error message. It seems to be looping on "Contents/MacOS/Praat.app/Contents....". Perhaps I'm missing something, but I thought it should stop at Praat.app instead of looping indefinitely.
I also tried to just set "/Applications" as the Path, but still got the error message.

**Comment by orhunulusahin** [comment]
Hello, thanks for opening the issue.

Version 0.11.0 of the extension overhauled the connection to and from Praat, and I've been able to confirm that running scripts through the extension correctly works on Linux (Arch and Debian) with both VSCode and VSCodium. It's likely that it now works better on OS X as well.

Could you update to 0.11.0 (VSCode probably automatically did this for you) and try to replicate the problem?

**Comment by Karlemami** [comment]
Hello,

I can confirm it now works on macOS X, thank you !
