### ISSUE TITLE
Detection of tags picks up variables names

### ISSUE THREAD

**Issue by stefanocoretta** [orhunulusahin/praatvscode#3]
Hi! Thanks for the extension, it's amazing. :)

I just noticed that the error detection partially matches tags in variable names.

For example, I am looking at Styler's [`NasalityAutomeasure.praat`](https://github.com/stylerw/styler_praat_scripts/blob/master/nasality_automeasure/NasalityAutomeasure.praat) script which has some variables called `formnum` and I get errors stating `for` is not matched by an `endfor` even though it is.

<img width="1440" alt="Screenshot 2024-02-11 at 13 13 49" src="https://github.com/orhunulusahin/praatvscode/assets/6429302/d8ecf99a-7b47-4ba6-adc7-5b91ea34c50e">

**Comment by orhunulusahin** [comment]
These tag pair checks used to rely on quick string comparisons of the first few characters of lines. Now they rely on regular expressions (as they probably should have from the start). Tested with the script you've linked to. Marking solved as of v0.11.1.

Thanks for the feedback!
