### ISSUE TITLE
false positive "unmatched endeditor" error

### ISSUE THREAD

**Issue by drammock** [orhunulusahin/praatvscode#5]
See screenshot below; editor is opened on line 48 and closed on line 54.  I suspect it's the colon that breaks the match detection?

![Screenshot_2024-03-04_13-25-21](https://github.com/orhunulusahin/praatvscode/assets/1810515/093c0588-bd25-4e41-b3b1-1cd519763253)

**Comment by drammock** [comment]
ps: script is here if you want it for testing or something: https://github.com/drammock/eeg-phone-coding/blob/master/stimulus-generation/mark-CV-boundaries.praat

**Comment by orhunulusahin** [comment]
Fixed in 0.11.2!
It was the colon indeed. The tag pairs now match correctly if they're followed by a Praat operator (colon or ellipsis).
Thank you!
